<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="../assets/images/Group 49.svg" type="image/x-icon">
    <link rel="stylesheet" href="../styles/product_actions.css">
    <link rel="stylesheet" href="../styles/agent_verification.css">

    <script async type="module" src="../scripts/agent_verification.js"></script>
    <script src="../scripts/qrcode.js"></script>

    <title>Agent verification</title>
</head>
<body>
    
    <div class="nav_panel">
        <div class="left_float">
            <img src="../assets/images/Group 145 copy.svg" alt="c_avatar" class="avatar">
        </div>
        
        <div class="right_float">

            <li class="profile_tabs account_profile">
                <a href="../directories/account_profile.html" class="picking_dir"> Account profile </a>
            </li>

            <li class="profile_tabs picking_product">
                <a href="http://" class="picking_dir"> Picking product </a>
            </li>

            <li class="profile_tabs fraud_awareness">
                <a href="../directories/fraud_awareness.html" class="picking_dir"> Fraud awareness </a>
            </li>

            <li class="profile_tabs dashboard">
                <a href="../directories/dashboard.html" class="picking_dir"> Dashboard </a>
            </li>


            <li class="profile_tabs username profile_username">Username</li>
            <img src="../assets/images/e0e69226-9ff0-4e4e-a0fe-5ad8555a07e8.jpg" alt="u_avatar" class="avatar u_avatar user_image_placeholder">
        </div>
        
    </div>

    <div class="product_activities_hero">

        <div class="product_activity_title">
            Agent verification
        </div>
        <img src="../assets/images/004-headphones.svg" alt="action_image" class="product_activity_image">
            
    </div>

    <form action="" method="post" class="product_delivery_registration delivery_agent_registration">

        <label for="p_name">Agent's name</label>
        <input type="text" placeholder="Please enter agent name" class="agent_name" name="agent_name">
        <label for="p_name_notifier" class="agent_name_error_notifier notifier">Please enter the agent's name</label>

        <label for="P_category"> Agent's email </label>
        <input type="text" placeholder="Please enter agent's email" class="agent_email" name="agent_email">
        <label for="p_category_notifier" class="agent_email_error_notifier notifier"> Please enter the agent's email </label>

       
        <label for="receiver_email"> Agent's phone number </label>
        <input type="text" placeholder="Please enter agent's phone number" class="agent_phone_number" name="agent_phone_number">
        <label for="r_email_notifier" class="agent_phone_number_error_notifier notifier"> Please enter agent's number </label>

        <label for="p_name">Product name</label>
        <input type="text" placeholder="Please enter product name" class="product_name" name="product_name">
        <label for="p_name_notifier" class="p_name_error_notifier notifier">Please enter the product name</label>

        <div class="p_quantity_delivery_number">

            <div class="product_quantity">

                <label for="p_quantity"> Product quantity </label>
                <input type="text" placeholder="Please enter product quantity" class="product_quantity_input" name="product_quantity">
                <label for="p_delivery_number_notifier" class="p_quantity_error_notifier notifier"> Please enter product quantity </label>
                
            </div>
            
        </div>

        <label for="p_image_upload"> Upload agent's image </label>
        <label for="upload" class="p_img_upload_lb"> Select image </label> 
        <input type="file" name="agent_picture_image" placeholder="Select image" class="agent_image_upload_button product_upload_button"> 
        
        <img src="../assets/images/033-user.svg" height="200px" alt="" class="p_image_placeholder agent_image_placeholder">
        <div class="form_loader"></div>

        <label for="image_upload_notifier" class="agent_image_upload_notifier notifier"> Please select image to upload </label>

        <label for="p_qr"> Autogenerated QR code </label>
        <div class="img_qr_code" style="width:35%; margin-left:32.5%; margin-bottom:1rem;"></div>

        <input type="text" name="agent_qr_code_string" placeholder="URL qr strings" id="qr_code_placeholder" class="qr_code_container">
        <button class="print_qr_pdf">Print QR</button>

        <button name="" class="product_delivery_submit_btn delivery_agent_submit_btn"> Submit </button>
        <div class="product_form_notifier agent_form_notifier"> </div>
           
    </form>


</body>
</html>